Repository dalyIsaac/Whim, pull requests merged in 2023-12, with the labels that each got.

#636 Fix window edge movement command values
  src/Whim.Tests/Commands/CoreCommandsTests.cs
  src/Whim/Commands/CoreCommands.cs
Labels: bug, core

#638 Force window focus (don't be nice and let windows dawdle)
  src/Whim.CommandPalette/CommandPaletteWindow.xaml.cs
  src/Whim.Tests/Window/WindowTests.cs
  src/Whim/Window/IWindow.cs
  src/Whim/Window/Window.cs
Labels: bug, core

#640 Consolidate on `IWindow.ProcessFileName`
  src/Whim.Bar.Tests/FocusedWindow/FocusedWindowWidget.test.xaml.cs
  src/Whim.Bar/FocusedWindow/FocusedWindowWidget.xaml.cs
  src/Whim.Tests/Router/FilterManagerTests.cs
  src/Whim.Tests/Router/RouterManagerTests.cs
  src/Whim/Context/Context.cs
  src/Whim/Router/DefaultFilteredWindows.cs
  src/Whim/Router/FilterManager.cs
  src/Whim/Router/IFilterManager.cs
  src/Whim/Router/IRouterManager.cs
  src/Whim/Router/RouterManager.cs
  src/Whim/Window/IWindow.cs
  src/Whim/Window/WindowManager.cs
Labels: refactor, core

#643 Save and restore workspaces
  README.md
  src/Whim.Tests/Context/CoreSavedStateManagerTests.cs
  src/Whim.Tests/Location/RectangleTests.cs
  src/Whim.Tests/Window/WindowManagerTests.cs
  src/Whim.Tests/Workspace/WorkspaceManagerTests.cs
  src/Whim/Context/CoreSavedStateManager.cs
  src/Whim/Context/ICoreSavedStateManager.cs
  src/Whim/Context/IInternalContext.cs
  src/Whim/Context/InternalContext.cs
  src/Whim/Location/IRectangle.cs
  src/Whim/Location/Rectangle.cs
  src/Whim/Window/IInternalWindowManager.cs
  src/Whim/Window/IWindow.cs
  src/Whim/Window/IWindowManager.cs
  src/Whim/Window/Window.cs
  src/Whim/Window/WindowManager.cs
  src/Whim/Workspace/WorkspaceManager.cs
Labels: refactor, core

#646 Update config to prevent floating windows being resized by the gaps plugin
  src/Whim/Template/whim.config.csx
Labels: bug, csx

#648 Add restart support
  src/Whim.Runner/App.xaml.cs
  src/Whim.Tests/Commands/CoreCommandsTests.cs
  src/Whim/Commands/CoreCommands.cs
Labels: enhancement, core

#650 Add placeholder file for Komorebi-sourced rules
  README.md
  src/Whim.Tests/Filter/FilterManagerTests.cs
  src/Whim.Tests/Keybind/KeyModifiersTests.cs
  src/Whim.Tests/Keybind/KeybindHookTests.cs
  src/Whim.Tests/Keybind/KeybindManagerTests.cs
  src/Whim.Tests/Keybind/KeybindTests.cs
  src/Whim/File/FileManager.cs
  src/Whim/File/IFileManager.cs
  src/Whim/Filter/DefaultFilteredWindows.cs
  src/Whim/Filter/DefaultFilteredWindowsKomorebi.g.cs
  src/Whim/Filter/FilterManager.cs
  src/Whim/Filter/IFilterManager.cs
  src/Whim/Keybind/IKeybind.cs
  src/Whim/Keybind/IKeybindHook.cs
  src/Whim/Keybind/IKeybindManager.cs
  src/Whim/Keybind/KeyModifiers.cs
  src/Whim/Keybind/Keybind.cs
  src/Whim/Keybind/KeybindHook.cs
  src/Whim/Keybind/KeybindManager.cs
  src/Whim/Keybind/VirtualKeyExtensions.cs
Labels: refactor, core

#654 Fix GitHub authentication in upgrade_app_rules workflow
  .github/workflows/upgrade_app_rules.yml
Labels: bug, github

#683 Reduce when release and commit workflows are run
  .github/workflows/commit.yml
  .github/workflows/release.yml
Labels: github

#686 Automated app-rules upgrades
  src/Whim/Filter/DefaultFilteredWindowsKomorebi.g.cs
Labels: auto app rules

#688 Add KeybindManager.RemoveAll()
  README.md
  src/Whim.CommandPalette/Variants/FreeText/FreeTextVariantView.xaml
  src/Whim.CommandPalette/Variants/Menu/MenuVariantView.xaml
  src/Whim.LayoutPreview/LayoutPreviewWindow.xaml
  src/Whim.Tests/Keybind/KeybindManagerTests.cs
  src/Whim/Keybind/IKeybindManager.cs
  src/Whim/Keybind/KeybindManager.cs
Labels: enhancement, core

#697 Fix line endings
  README.md
  src/Whim.CommandPalette/Variants/FreeText/FreeTextVariantView.xaml
  src/Whim.CommandPalette/Variants/Menu/MenuVariantView.xaml
  src/Whim.LayoutPreview/LayoutPreviewWindow.xaml
  src/Whim.Tests/Keybind/KeybindManagerTests.cs
Labels: refactor

#693 Clear `ProcessFileName` properly
  src/Whim.Tests/Filter/FilterManagerTests.cs
  src/Whim/Filter/FilterManager.cs
Labels: bug, core

#695 Rename `IKeybindManager.RemoveAll` to `Clear`
  README.md
  src/Whim.Tests/Keybind/KeybindManagerTests.cs
  src/Whim/Keybind/IKeybindManager.cs
  src/Whim/Keybind/KeybindManager.cs
Labels: refactor, core

#698 Do not load workspaces from state if config has changed
  .github/workflows/release.yml
  src/Whim.Tests/Workspace/WorkspaceManagerTests.cs
  src/Whim/Workspace/WorkspaceManager.cs
Labels: bug, core

#704 Automated app-rules upgrades
  src/Whim/Filter/DefaultFilteredWindowsKomorebi.g.cs
Labels: auto app rules

#705 Add the ability to focus adjacent monitors with empty workspaces
  Directory.Packages.props
  README.md
  src/Whim.Tests/Commands/CoreCommandsTests.cs
  src/Whim.Tests/Monitor/MonitorManagerTests.cs
  src/Whim.Tests/Workspace/WorkspaceTests.cs
  src/Whim/Commands/CoreCommands.cs
  src/Whim/Context/Context.cs
  src/Whim/Keybind/KeybindManager.cs
  src/Whim/Monitor/IInternalMonitorManager.cs
  src/Whim/Monitor/MonitorManager.cs
  src/Whim/Native/CoreNativeManager.cs
  src/Whim/Native/ICoreNativeManager.cs
  src/Whim/Workspace/IWorkspace.cs
  src/Whim/Workspace/Workspace.cs
Labels: bug, core

#706 Whim can now add minimized windows again
  src/Whim/Native/NativeManager.cs
  src/Whim/Window/WindowManager.cs
Labels: bug, core

#708 Delete core saved state after load
  src/Whim.Tests/Context/CoreSavedStateManagerTests.cs
  src/Whim/Context/CoreSavedStateManager.cs
  src/Whim/File/FileManager.cs
  src/Whim/File/IFileManager.cs
Labels: bug, core

#713 Automated app-rules upgrades
  src/Whim/Filter/DefaultFilteredWindowsKomorebi.g.cs
Labels: auto app rules

#721 Add `INotificationManager` to facilitate toast notifications
  src/Whim.Runner/App.xaml.cs
  src/Whim/Context/Context.cs
  src/Whim/Context/IContext.cs
  src/Whim/Notification/INotificationManager.cs
  src/Whim/Notification/NotificationManager.cs
Labels: enhancement, core

#722 Automated app-rules upgrades
  src/Whim/Filter/DefaultFilteredWindowsKomorebi.g.cs
Labels: auto app rules

#724 [UNSTABLE] Add auto-updater
  .github/release.yml
  Directory.Packages.props
  README.md
  Whim.sln
  docs/dev-process.md
  src/Directory.Build.props
  src/Whim.Bar/ActiveLayout/NextLayoutEngineCommand.cs
  src/Whim.CommandPalette/ExecuteCommand.cs
  src/Whim.Runner/App.xaml.cs
  src/Whim.Runner/Whim.Runner.csproj
  src/Whim.Tests/Monitor/MonitorManagerTests.cs
  src/Whim.Tests/Window/WindowManagerTests.cs
  src/Whim.TreeLayout.Bar/ToggleDirectionCommand.cs
  src/Whim.Updater.Tests/GlobalSuppressions.cs
  src/Whim.Updater.Tests/UpdaterCommandsTests.cs
  src/Whim.Updater.Tests/UpdaterConfigTests.cs
  src/Whim.Updater.Tests/UpdaterPluginTests.cs
  src/Whim.Updater.Tests/UpdaterWindow/Data.cs
  src/Whim.Updater.Tests/UpdaterWindow/GitHubUserProfileExtensionTests.cs
  src/Whim.Updater.Tests/UpdaterWindow/UpdaterWindowViewModelTests.cs
  src/Whim.Updater.Tests/VersionTests.cs
  src/Whim.Updater.Tests/Whim.Updater.Tests.csproj
  src/Whim.Updater/IUpdaterPlugin.cs
  src/Whim.Updater/ReleaseInfo.cs
  src/Whim.Updater/UpdaterCommands.cs
  src/Whim.Updater/UpdaterConfig.cs
  src/Whim.Updater/UpdaterPlugin.cs
  src/Whim.Updater/UpdaterWindow/GitHubUserProfileExtension.cs
  src/Whim.Updater/UpdaterWindow/UpdaterWindow.xaml
  src/Whim.Updater/UpdaterWindow/UpdaterWindow.xaml.cs
  src/Whim.Updater/UpdaterWindow/UpdaterWindowCommands.cs
  src/Whim.Updater/UpdaterWindow/UpdaterWindowViewModel.cs
  src/Whim.Updater/Version.cs
  src/Whim.Updater/Whim.Updater.csproj
  src/Whim/Context/ExitReason.cs
  src/Whim/Monitor/MonitorManager.cs
  src/Whim/Native/CoreNativeManager.cs
  src/Whim/Native/ICoreNativeManager.cs
  src/Whim/Native/INativeManager.cs
  src/Whim/Native/NativeManager.cs
  src/Whim/Template/whim.config.csx
  src/Whim/Window/WindowManager.cs
Labels: enhancement, plugin idea

#726 Bump Whim version to 0.2.0
  src/Whim.Bar.Tests/Whim.Bar.Tests.csproj
  src/Whim.Bar/Whim.Bar.csproj
  src/Whim.CommandPalette.Tests/Whim.CommandPalette.Tests.csproj
  src/Whim.CommandPalette/Whim.CommandPalette.csproj
  src/Whim.FloatingLayout.Tests/Whim.FloatingLayout.Tests.csproj
  src/Whim.FloatingLayout/Whim.FloatingLayout.csproj
  src/Whim.FocusIndicator/Whim.FocusIndicator.csproj
  src/Whim.Gaps.Tests/Whim.Gaps.Tests.csproj
  src/Whim.Gaps/Whim.Gaps.csproj
  src/Whim.LayoutPreview.Tests/Whim.LayoutPreview.Tests.csproj
  src/Whim.LayoutPreview/Whim.LayoutPreview.csproj
  src/Whim.Runner/Whim.Runner.csproj
  src/Whim.TestUtils/Whim.TestUtils.csproj
  src/Whim.Tests/Whim.Tests.csproj
  src/Whim.TreeLayout.Bar.Tests/Whim.TreeLayout.Bar.Tests.csproj
  src/Whim.TreeLayout.Bar/Whim.TreeLayout.Bar.csproj
  src/Whim.TreeLayout.CommandPalette.Tests/Whim.TreeLayout.CommandPalette.Tests.csproj
  src/Whim.TreeLayout.CommandPalette/Whim.TreeLayout.CommandPalette.csproj
  src/Whim.TreeLayout.Tests/Whim.TreeLayout.Tests.csproj
  src/Whim.TreeLayout/Whim.TreeLayout.csproj
  src/Whim.Updater.Tests/Whim.Updater.Tests.csproj
  src/Whim.Updater/Whim.Updater.csproj
  src/Whim/Whim.csproj
Labels: whim version

#727 Remove unused `using`
  src/Whim.Runner/App.xaml.cs
  src/Whim/Native/CoreNativeManager.cs
Labels: refactor

#723 `Whim.Bar` styler
  src/Whim.Bar/ActiveLayout/ActiveLayoutWidget.xaml
  src/Whim.Bar/BarConfig.cs
  src/Whim.Bar/BarWindow.xaml
  src/Whim.Bar/DateTime/DateTimeWidget.xaml
  src/Whim.Bar/FocusedWindow/FocusedWindowWidget.xaml
  src/Whim.Bar/Workspace/WorkspaceWidget.xaml
  src/Whim.TreeLayout.Bar/TreeLayoutEngineWidget.xaml
  src/Whim/Context/Context.cs
  src/Whim/Context/IContext.cs
  src/Whim/Resources/Defaults.xaml
  src/Whim/Resources/IResourceManager.cs
  src/Whim/Resources/ResourceManager.cs
  src/Whim/Whim.csproj
Labels: enhancement, bar

#732 feat: `WorkspaceManager.SwapActiveWorkspaceWithNextMonitor` (#661)
  src/Whim.Tests/Workspace/WorkspaceManagerTests.cs
  src/Whim/Workspace/IWorkspaceManager.cs
  src/Whim/Workspace/WorkspaceManager.cs
Labels: enhancement, core

#736 Let `ILayoutEngine`s perform custom actions
  src/Whim.Bar.Tests/BarLayoutEngineTests.cs
  src/Whim.Bar/BarLayoutEngine.cs
  src/Whim.FloatingLayout.Tests/FloatingLayoutEngineTests.cs
  src/Whim.FloatingLayout/FloatingLayoutEngine.cs
  src/Whim.Gaps.Tests/GapsLayoutEngineTests.cs
  src/Whim.Gaps/GapsLayoutEngine.cs
  src/Whim.TestUtils/ProxyLayoutEngineBaseTests.cs
  src/Whim.TestUtils/TestLayoutEngine.cs
  src/Whim.Tests/Layout/ColumnLayoutEngineTests.cs
  src/Whim.Tests/Workspace/WorkspaceTests.cs
  src/Whim.TreeLayout.Tests/LayoutEngine/PerformCustomActionTests.cs
  src/Whim.TreeLayout/TreeLayoutEngine.cs
  src/Whim/Layout/BaseProxyLayoutEngine.cs
  src/Whim/Layout/ColumnLayoutEngine.cs
  src/Whim/Layout/ILayoutEngine.cs
  src/Whim/Layout/LayoutEngineCustomAction.cs
  src/Whim/Workspace/IWorkspace.cs
  src/Whim/Workspace/Workspace.cs
Labels: enhancement, core

#742 Add missing documentation
  src/Directory.Build.props
  src/Whim.TestUtils/Directory.Build.props
  src/Whim.TreeLayout.Bar/ToggleDirectionCommand.cs
  src/Whim.TreeLayout.Tests/TreeLayoutCommandsTests.cs
  src/Whim.TreeLayout.Tests/Utils/LayoutEngineWrapper.cs
  src/Whim.TreeLayout.Tests/Utils/SimpleTestTree.cs
  src/Whim.TreeLayout.Tests/Utils/TestTree.cs
  src/Whim.TreeLayout/ITreeLayoutPlugin.cs
  src/Whim.TreeLayout/TreeLayoutEngine.cs
  src/Whim.Updater.Tests/Directory.Build.props
  src/Whim/Layout/ColumnLayoutEngine.cs
  src/Whim/Workspace/IWorkspace.cs
Labels: documentation

#743 Bump Whim version to 0.3.0
  src/Whim.Bar.Tests/Whim.Bar.Tests.csproj
  src/Whim.Bar/Whim.Bar.csproj
  src/Whim.CommandPalette.Tests/Whim.CommandPalette.Tests.csproj
  src/Whim.CommandPalette/Whim.CommandPalette.csproj
  src/Whim.FloatingLayout.Tests/Whim.FloatingLayout.Tests.csproj
  src/Whim.FloatingLayout/Whim.FloatingLayout.csproj
  src/Whim.FocusIndicator/Whim.FocusIndicator.csproj
  src/Whim.Gaps.Tests/Whim.Gaps.Tests.csproj
  src/Whim.Gaps/Whim.Gaps.csproj
  src/Whim.LayoutPreview.Tests/Whim.LayoutPreview.Tests.csproj
  src/Whim.LayoutPreview/Whim.LayoutPreview.csproj
  src/Whim.Runner/Whim.Runner.csproj
  src/Whim.TestUtils/Whim.TestUtils.csproj
  src/Whim.Tests/Whim.Tests.csproj
  src/Whim.TreeLayout.Bar.Tests/Whim.TreeLayout.Bar.Tests.csproj
  src/Whim.TreeLayout.Bar/Whim.TreeLayout.Bar.csproj
  src/Whim.TreeLayout.CommandPalette.Tests/Whim.TreeLayout.CommandPalette.Tests.csproj
  src/Whim.TreeLayout.CommandPalette/Whim.TreeLayout.CommandPalette.csproj
  src/Whim.TreeLayout.Tests/Whim.TreeLayout.Tests.csproj
  src/Whim.TreeLayout/Whim.TreeLayout.csproj
  src/Whim.Updater.Tests/Whim.Updater.Tests.csproj
  src/Whim.Updater/Whim.Updater.csproj
  src/Whim/Whim.csproj
Labels: whim version

#744 Try to route to the active workspace
  README.md
  src/Whim.Tests/Router/RouterManagerTests.cs
  src/Whim.Tests/Workspace/WorkspaceManagerTests.cs
  src/Whim/Monitor/IInternalMonitorManager.cs
  src/Whim/Monitor/MonitorManager.cs
  src/Whim/Router/IRouterManager.cs
  src/Whim/Router/RouterManager.cs
  src/Whim/Router/RouterOptions.cs
  src/Whim/Workspace/WorkspaceManager.cs
Labels: bug, core

#745 Update local build docs
  README.md
Labels: documentation

#749 Bump Whim version to 0.4.0
  src/Whim.Bar.Tests/Whim.Bar.Tests.csproj
  src/Whim.Bar/Whim.Bar.csproj
  src/Whim.CommandPalette.Tests/Whim.CommandPalette.Tests.csproj
  src/Whim.CommandPalette/Whim.CommandPalette.csproj
  src/Whim.FloatingLayout.Tests/Whim.FloatingLayout.Tests.csproj
  src/Whim.FloatingLayout/Whim.FloatingLayout.csproj
  src/Whim.FocusIndicator/Whim.FocusIndicator.csproj
  src/Whim.Gaps.Tests/Whim.Gaps.Tests.csproj
  src/Whim.Gaps/Whim.Gaps.csproj
  src/Whim.LayoutPreview.Tests/Whim.LayoutPreview.Tests.csproj
  src/Whim.LayoutPreview/Whim.LayoutPreview.csproj
  src/Whim.Runner/Whim.Runner.csproj
  src/Whim.SliceLayout.Tests/Whim.SliceLayout.Tests.csproj
  src/Whim.SliceLayout/Whim.SliceLayout.csproj
  src/Whim.TestUtils/Whim.TestUtils.csproj
  src/Whim.Tests/Whim.Tests.csproj
  src/Whim.TreeLayout.Bar.Tests/Whim.TreeLayout.Bar.Tests.csproj
  src/Whim.TreeLayout.Bar/Whim.TreeLayout.Bar.csproj
  src/Whim.TreeLayout.CommandPalette.Tests/Whim.TreeLayout.CommandPalette.Tests.csproj
  src/Whim.TreeLayout.CommandPalette/Whim.TreeLayout.CommandPalette.csproj
  src/Whim.TreeLayout.Tests/Whim.TreeLayout.Tests.csproj
  src/Whim.TreeLayout/Whim.TreeLayout.csproj
  src/Whim.Updater.Tests/Whim.Updater.Tests.csproj
  src/Whim.Updater/Whim.Updater.csproj
  src/Whim/Whim.csproj
Labels: whim version

#748 `ILayoutEngine.FocusWindowInDirection` now returns `ILayoutEngine`
  src/Whim.Bar.Tests/BarLayoutEngineTests.cs
  src/Whim.Bar/BarLayoutEngine.cs
  src/Whim.FloatingLayout.Tests/FloatingLayoutEngineTests.cs
  src/Whim.FloatingLayout/FloatingLayoutEngine.cs
  src/Whim.Gaps.Tests/GapsLayoutEngineTests.cs
  src/Whim.Gaps/GapsLayoutEngine.cs
  src/Whim.SliceLayout.Tests/SliceLayoutEngine/FocusWindowInDirectionTests.cs
  src/Whim.SliceLayout/SliceLayoutEngine.cs
  src/Whim.TestUtils/TestLayoutEngine.cs
  src/Whim.Tests/Workspace/WorkspaceTests.cs
  src/Whim.TreeLayout/TreeLayoutEngine.cs
  src/Whim/Layout/BaseProxyLayoutEngine.cs
  src/Whim/Layout/ColumnLayoutEngine.cs
  src/Whim/Layout/ILayoutEngine.cs
  src/Whim/Workspace/Workspace.cs
Labels: enhancement, core
