Repository dalyIsaac/Whim, pull requests merged in 2024-08, with the labels that each got.

#959 Change focus indicator to polling
  src/Whim.FocusIndicator/FocusIndicatorPlugin.cs
  src/Whim.FocusIndicator/FocusIndicatorWindow.xaml
  src/Whim.FocusIndicator/FocusIndicatorWindow.xaml.cs
  src/Whim.Tests/Store/WorkspaceSector/WorkspacePickersTests.cs
  src/Whim/Native/DeferWindowPosHandle.cs
  src/Whim/Native/NativeManager.cs
  src/Whim/Store/Store.cs
  src/Whim/Store/WorkspaceSector/WorkspacePickers.cs
Labels: bug, focus indicator

#960 Switch to a timer-based approach for Firefox handling
  src/Whim.Tests/Store/WindowSector/Processors/FirefoxWindowProcessorTests.cs
  src/Whim.Tests/Store/WindowSector/Processors/WindowProcessorManagerTests.cs
  src/Whim/Store/WindowSector/Processors/FirefoxWindowProcessor.cs
  src/Whim/Store/WindowSector/Processors/WindowProcessorManager.cs
  src/Whim/Store/WindowSector/Processors/WindowProcessorResult.cs
Labels: bug, core

#963 Always hide layout preview when missing Windows events
  src/Whim.LayoutPreview.Tests/LayoutPreviewPluginTests.cs
  src/Whim.LayoutPreview/LayoutPreviewPlugin.cs
  src/Whim.LayoutPreview/LayoutPreviewWindow.xaml
  src/Whim.LayoutPreview/LayoutPreviewWindow.xaml.cs
  src/Whim.TestUtils/StoreCustomization.cs
  src/Whim.TestUtils/StoreTestUtils.cs
  src/Whim.TestUtils/Whim.TestUtils.csproj
  src/Whim.Tests/Store/MapSector/Transforms/MoveWindowToPointTransformTests.cs
  src/Whim/Store/MapSector/Transforms/MoveWindowToPointTransform.cs
Labels: bug, layout preview

#964 Bump Whim version to 0.7.0
  src/Whim.Bar.Tests/Whim.Bar.Tests.csproj
  src/Whim.Bar/Whim.Bar.csproj
  src/Whim.CommandPalette.Tests/Whim.CommandPalette.Tests.csproj
  src/Whim.CommandPalette/Whim.CommandPalette.csproj
  src/Whim.FloatingLayout.Tests/Whim.FloatingLayout.Tests.csproj
  src/Whim.FloatingLayout/Whim.FloatingLayout.csproj
  src/Whim.FocusIndicator/Whim.FocusIndicator.csproj
  src/Whim.Gaps.Tests/Whim.Gaps.Tests.csproj
  src/Whim.Gaps/Whim.Gaps.csproj
  src/Whim.LayoutPreview.Tests/Whim.LayoutPreview.Tests.csproj
  src/Whim.LayoutPreview/Whim.LayoutPreview.csproj
  src/Whim.Runner/Whim.Runner.csproj
  src/Whim.SliceLayout.Tests/Whim.SliceLayout.Tests.csproj
  src/Whim.SliceLayout/Whim.SliceLayout.csproj
  src/Whim.TestUtils/Whim.TestUtils.csproj
  src/Whim.Tests/Whim.Tests.csproj
  src/Whim.TreeLayout.Bar.Tests/Whim.TreeLayout.Bar.Tests.csproj
  src/Whim.TreeLayout.Bar/Whim.TreeLayout.Bar.csproj
  src/Whim.TreeLayout.CommandPalette.Tests/Whim.TreeLayout.CommandPalette.Tests.csproj
  src/Whim.TreeLayout.CommandPalette/Whim.TreeLayout.CommandPalette.csproj
  src/Whim.TreeLayout.Tests/Whim.TreeLayout.Tests.csproj
  src/Whim.TreeLayout/Whim.TreeLayout.csproj
  src/Whim.Updater.Tests/Whim.Updater.Tests.csproj
  src/Whim.Updater/Whim.Updater.csproj
  src/Whim/Whim.csproj
Labels: whim version

#965 Upgrade to .NET 8
  .gitignore
  .vscode/launch.json
  docs/docs/contribute/development.md
  docs/docs/getting-started/customize.md
  omnisharp.json
  scripts/Create-Installer.ps1
  src/Whim.Bar.Tests/Whim.Bar.Tests.csproj
  src/Whim.Bar/Whim.Bar.csproj
  src/Whim.CommandPalette.Tests/Whim.CommandPalette.Tests.csproj
  src/Whim.CommandPalette/Whim.CommandPalette.csproj
  src/Whim.FloatingWindow.Tests/Whim.FloatingWindow.Tests.csproj
  src/Whim.FloatingWindow/Whim.FloatingWindow.csproj
  src/Whim.FocusIndicator/Whim.FocusIndicator.csproj
  src/Whim.Gaps.Tests/Whim.Gaps.Tests.csproj
  src/Whim.Gaps/Whim.Gaps.csproj
  src/Whim.LayoutPreview.Tests/Whim.LayoutPreview.Tests.csproj
  src/Whim.LayoutPreview/Whim.LayoutPreview.csproj
  src/Whim.Runner/Properties/PublishProfiles/win-arm64.pubxml
  src/Whim.Runner/Properties/PublishProfiles/win-x64.pubxml
  src/Whim.Runner/Properties/launchSettings.json
  src/Whim.Runner/Whim.Runner.csproj
  src/Whim.SliceLayout.Tests/Whim.SliceLayout.Tests.csproj
  src/Whim.SliceLayout/Whim.SliceLayout.csproj
  src/Whim.TestUtils/StoreTestUtils.cs
  src/Whim.TestUtils/Whim.TestUtils.csproj
  src/Whim.Tests/Store/Root/StoreTests.cs
  src/Whim.Tests/Whim.Tests.csproj
  src/Whim.TreeLayout.Bar.Tests/Whim.TreeLayout.Bar.Tests.csproj
  src/Whim.TreeLayout.Bar/Whim.TreeLayout.Bar.csproj
  src/Whim.TreeLayout.CommandPalette.Tests/Whim.TreeLayout.CommandPalette.Tests.csproj
  src/Whim.TreeLayout.CommandPalette/Whim.TreeLayout.CommandPalette.csproj
  src/Whim.TreeLayout.Tests/Whim.TreeLayout.Tests.csproj
  src/Whim.TreeLayout/Whim.TreeLayout.csproj
  src/Whim.Updater.Tests/Whim.Updater.Tests.csproj
  src/Whim.Updater/Whim.Updater.csproj
  src/Whim/Whim.csproj
Labels: engineering

#966 Update dependencies for .NET 8
  Directory.Packages.props
  src/Whim.Bar.Tests/Whim.Bar.Tests.csproj
  src/Whim.Tests/Whim.Tests.csproj
  src/Whim.Tests/Window/WindowTests.cs
  src/Whim/Butler/ButlerPantry.cs
  src/Whim/Monitor/MonitorManager.cs
  src/Whim/Store/MapSector/Transforms/ActivateWorkspaceTransform.cs
  src/Whim/Store/WindowSector/Transforms/WindowAddedTransform.cs
  src/Whim/Window/WindowManager.cs
  src/Whim/Workspace/LegacyWorkspace.cs
  src/Whim/Workspace/WorkspaceManager.cs
Labels: dependencies, engineering

#967 Extract UpdateWindowRectangle from Floating and ProxyFloating layout
  src/Whim.FloatingWindow/FloatingLayoutEngine.cs
  src/Whim.FloatingWindow/FloatingUtils.cs
  src/Whim.FloatingWindow/ProxyFloatingLayoutEngine.cs
Labels: refactor, floating windows

#973 Significantly simplify UpdaterPlugin
  Directory.Packages.props
  docs/docs/plugins/updater.md
  docs/index.md
  src/Whim.Tests/Store/Root/SavedStateTransformTests.cs
  src/Whim.Updater.Tests/Data.cs
  src/Whim.Updater.Tests/ReleaseManagerTests.cs
  src/Whim.Updater.Tests/UpdaterPluginTests.cs
  src/Whim.Updater.Tests/UpdaterWindow/GitHubUserProfileExtensionTests.cs
  src/Whim.Updater.Tests/UpdaterWindow/UpdaterWindowViewModelTests.cs
  src/Whim.Updater.Tests/VersionTests.cs
  src/Whim.Updater/IUpdaterPlugin.cs
  src/Whim.Updater/ReleaseManager.cs
  src/Whim.Updater/UpdaterConfig.cs
  src/Whim.Updater/UpdaterPlugin.cs
  src/Whim.Updater/UpdaterWindow/GitHubUserProfileExtension.cs
  src/Whim.Updater/UpdaterWindow/UpdaterWindow.xaml
  src/Whim.Updater/UpdaterWindow/UpdaterWindow.xaml.cs
  src/Whim.Updater/UpdaterWindow/UpdaterWindowCommands.cs
  src/Whim.Updater/UpdaterWindow/UpdaterWindowViewModel.cs
  src/Whim.Updater/Version.cs
  src/Whim.Updater/Whim.Updater.csproj
  src/Whim/Native/INativeManager.cs
  src/Whim/Native/NativeManager.cs
  src/Whim/Plugin/IPluginManager.cs
  src/Whim/Plugin/PluginManager.cs
  src/Whim/Store/RootSector/Transforms/SaveStateTransform.cs
Labels: updater

#975 Add `MoveWindowToMonitorIndexTransform`
  src/Whim.Tests/Store/MapSector/Transforms/MoveWindowToMonitorIndexTransformTests.cs
  src/Whim.Tests/Store/MonitorSector/MonitorPickersTests.cs
  src/Whim/Store/MapSector/Transforms/MoveWindowToMonitorIndexTransform.cs
  src/Whim/Store/MonitorSector/IMonitorSector.cs
  src/Whim/Store/MonitorSector/MonitorPickers.cs
  src/Whim/Store/StoreExceptions.cs
Labels: enhancement, core

#977 Always expose the workspace id when adding a workspace
  docs/docs/customize/snippets.md
  src/Whim.Tests/Store/MapSector/Transforms/InitializeWorkspacesTransformTests.cs
  src/Whim.Tests/Store/MonitorSector/Transforms/MonitorsChangedTransformTests.cs
  src/Whim.Tests/Store/WorkspaceSector/Transforms/AddWorkspaceTransformTests.cs
  src/Whim/Store/MonitorSector/Transforms/MonitorsChangedTransform.cs
  src/Whim/Store/WorkspaceSector/Transforms/AddWorkspaceTransform.cs
  src/Whim/Store/WorkspaceSector/Transforms/InitializeWorkspacesTransform.cs
  src/Whim/Store/WorkspaceSector/WorkspaceSector.cs
  src/Whim/Workspace/IWorkspaceManager.cs
  src/Whim/Workspace/WorkspaceManager.cs
Labels: enhancement, core

#979 Open workspaces on a specific monitor without activation
  docs/docs/customize/snippets.md
  src/Whim.TestUtils/StoreCustomization.cs
  src/Whim.Tests/Store/MapSector/Transforms/ActivateWorkspaceTransformTests.cs
  src/Whim/Store/MapSector/Transforms/ActivateWorkspaceTransform.cs
Labels: enhancement, core

#981 Update docs
  docs/docs/architecture/context.md
  docs/docs/architecture/deprecated.md
  docs/docs/architecture/events.md
  docs/docs/architecture/result.md
  docs/docs/architecture/store.md
  docs/docs/architecture/threading.md
  docs/docs/customize/commands.md
  docs/docs/customize/layout-engines.md
  docs/docs/customize/monitors.md
  docs/docs/customize/snippets.md
  docs/docs/customize/store.md
  docs/docs/customize/workspaces.md
  docs/docs/getting-started/comparison.md
  docs/docs/getting-started/troubleshooting.md
  docs/docs/plugins/floating-window.md
  docs/docs/plugins/slice-layout.md
  docs/docs/plugins/tree-layout.md
  docs/docs/toc.yml
  docs/images/example-monitor-layout.png
  src/Whim/Store/Store.cs
  src/Whim/Store/Transform.cs
  src/Whim/Store/WindowSector/Transforms/WindowAddedTransform.cs
  src/Whim/Template/whim.config.csx
Labels: documentation, skip release

#983 More docs improvements
  docs/docs/customize/monitors.md
  docs/docs/customize/snippets.md
  docs/docs/customize/store.md
  docs/docs/customize/workspaces.md
  src/Whim/Store/IStore.cs
  src/Whim/Store/MapSector/MapPickers.cs
  src/Whim/Store/MonitorSector/MonitorPickers.cs
  src/Whim/Store/WorkspaceSector/WorkspacePickers.cs
  src/Whim/Template/whim.config.csx
Labels: documentation, core

#984 Focus last focused window when switching to a layout engine
  src/Whim.Tests/Store/WorkspaceSector/WorkspaceSectorTests.cs
  src/Whim.Tests/Store/WorkspaceSector/WorkspaceUtilsTests.cs
  src/Whim/Native/NativeManager.cs
  src/Whim/Store/WindowSector/Transforms/WindowMinimizeEndedTransform.cs
  src/Whim/Store/WorkspaceSector/WorkspaceSector.cs
  src/Whim/Store/WorkspaceSector/WorkspaceUtils.cs
Labels: enhancement, core

#985 Mark `ColumnLayoutEngine` as deprecated
  docs/docs/customize/layout-engines.md
  src/Whim.SliceLayout.Tests/SliceLayoutsTests.cs
  src/Whim.SliceLayout/SliceLayouts.cs
  src/Whim.Tests/Store/Root/MutableRootSectorTests.cs
  src/Whim.Tests/Store/WorkspaceSector/Transforms/AddWorkspaceTransformTests.cs
  src/Whim/Layout/ColumnLayoutEngine.cs
  src/Whim/Store/WorkspaceSector/WorkspaceSector.cs
Labels: refactor, core

#991 Deprecate managers
  src/Whim.TestUtils/StoreTestUtils.cs
  src/Whim.Tests/Store/MapSector/Transforms/ActivateWorkspaceTransformTests.cs
  src/Whim.Tests/Store/WorkspaceSector/Transforms/ActivateLayoutEngineTransformTests.cs
  src/Whim.Tests/Store/WorkspaceSector/Transforms/FocusWindowInDirectionTransformTests.cs
  src/Whim.Tests/Store/WorkspaceSector/Transforms/FocusWindowTransformTests.cs
  src/Whim.Tests/Store/WorkspaceSector/Transforms/FocusWorkspaceTransformTests.cs
  src/Whim.Tests/Store/WorkspaceSector/Transforms/SwapWIndowInDirectionTransformTests.cs
  src/Whim.Tests/Store/WorkspaceSector/WorkspacePickersTests.cs
  src/Whim.Tests/Workspace/LegacyWorkspaceTests.cs
  src/Whim.Tests/Workspace/WorkspaceManagerTests.cs
  src/Whim/Butler/IButler.cs
  src/Whim/Butler/IButlerChores.cs
  src/Whim/Monitor/IMonitorManager.cs
  src/Whim/Store/IStore.cs
  src/Whim/Store/MapSector/Transforms/ActivateWorkspaceTransform.cs
  src/Whim/Store/Store.cs
  src/Whim/Store/StoreExceptions.cs
  src/Whim/Store/WorkspaceSector/Transforms/ActivateLayoutEngineTransform.cs
  src/Whim/Store/WorkspaceSector/Transforms/AddWindowToWorkspaceTransform.cs
  src/Whim/Store/WorkspaceSector/Transforms/BaseWorkspaceWindowTransform.cs
  src/Whim/Store/WorkspaceSector/Transforms/DoWorkspaceLayoutTransform.cs
  src/Whim/Store/WorkspaceSector/Transforms/FocusWindowInDirectionTransform.cs
  src/Whim/Store/WorkspaceSector/Transforms/FocusWindowTransform.cs
  src/Whim/Store/WorkspaceSector/Transforms/FocusWorkspaceTransform.cs
  src/Whim/Store/WorkspaceSector/Transforms/RemoveWindowFromWorkspaceTransform.cs
  src/Whim/Store/WorkspaceSector/Transforms/SwapWindowInDirectionTransform.cs
  src/Whim/Store/WorkspaceSector/WorkspacePickers.cs
  src/Whim/Store/WorkspaceSector/WorkspaceSector.cs
  src/Whim/Utils/Pred.cs
  src/Whim/Window/IWindowManager.cs
  src/Whim/Workspace/IWorkspace.cs
  src/Whim/Workspace/IWorkspaceManager.cs
  src/Whim/Workspace/LegacyWorkspace.cs
  src/Whim/Workspace/WorkspaceManager.cs
Labels: refactor, core

#997 Remove deprecated items use inside `CoreCommands`
  src/Whim.TestUtils/StoreTestUtils.cs
  src/Whim.TestUtils/WorkspaceUtils.cs
  src/Whim.Tests/Commands/CoreCommandsTests.cs
  src/Whim.Tests/Layout/ColumnLayoutEngineTests.cs
  src/Whim.Tests/Store/WorkspaceSector/Transforms/BaseWorkspaceTransformTests.cs
  src/Whim.Tests/Store/WorkspaceSector/WorkspaceUtilsTests.cs
  src/Whim/Butler/Butler.cs
  src/Whim/Commands/CoreCommands.cs
  src/Whim/Context/Context.cs
  src/Whim/Context/IContext.cs
  src/Whim/Store/WorkspaceSector/Transforms/BaseWorkspaceTransform.cs
  src/Whim/Store/WorkspaceSector/Transforms/CycleLayoutEngineTransform.cs
  src/Whim/Store/WorkspaceSector/Transforms/FocusWindowInDirectionTransform.cs
  src/Whim/Store/WorkspaceSector/Transforms/SwapWindowInDirectionTransform.cs
  src/Whim/Store/WorkspaceSector/WorkspacePickers.cs
  src/Whim/Store/WorkspaceSector/WorkspaceUtils.cs
Labels: refactor, core

#1002 Fix accidental deactivation of the wrong workspace
  src/Whim.Tests/Store/MapSector/Transforms/ActivateWorkspaceTransformTests.cs
  src/Whim/Store/MapSector/Transforms/ActivateWorkspaceTransform.cs
Labels: bug, core

#1004 Restart focus indicator when monitors change
  src/Whim.FocusIndicator/FocusIndicatorPlugin.cs
Labels: bug, core
