Repository dalyIsaac/Whim, pull requests merged in 2024-02, with the labels that each got.

#820 Automated app-rules upgrades
  src/Whim/Filter/DefaultFilteredWindowsKomorebi.g.cs
Labels: auto app rules

#824 Try avoid moving windows when removing/adding monitors
  docs/docs/getting-started/comparison.md
  docs/docs/getting-started/troubleshooting.md
  src/Whim.Bar.Tests/BarPluginTests.cs
  src/Whim.Bar/BarPlugin.cs
  src/Whim.TestUtils/NativeManagerUtils.cs
  src/Whim.Tests/Butler/ButlerEventHandlersTests.cs
  src/Whim.Tests/Butler/ButlerTests.cs
  src/Whim.Tests/Monitor/MonitorManagerTests.cs
  src/Whim.Tests/Window/WindowManagerTests.cs
  src/Whim.Tests/Workspace/WorkspaceManagerTests.cs
  src/Whim/Butler/Butler.cs
  src/Whim/Butler/ButlerEventHandlers.cs
  src/Whim/Butler/IButler.cs
  src/Whim/Butler/IButlerEventHandlers.cs
  src/Whim/Context/Context.cs
  src/Whim/Context/IInternalContext.cs
  src/Whim/Context/InternalContext.cs
  src/Whim/Monitor/IInternalMonitorManager.cs
  src/Whim/Monitor/IMonitorManager.cs
  src/Whim/Monitor/MonitorManager.cs
  src/Whim/Window/WindowManager.cs
Labels: bug, core

#827 Retain monitor focus when switching to an empty workspace
  src/Whim.Tests/Butler/ButlerChoresTests.cs
  src/Whim.Tests/Butler/ButlerEventHandlersTests.cs
  src/Whim.Tests/Window/WindowManagerTests.cs
  src/Whim.Tests/Workspace/WorkspaceManagerTests.cs
  src/Whim.Tests/Workspace/WorkspaceTests.cs
  src/Whim/Butler/Butler.cs
  src/Whim/Butler/ButlerChores.cs
  src/Whim/Butler/ButlerEventHandlers.cs
  src/Whim/Butler/IButlerChores.cs
  src/Whim/Butler/IButlerEventHandlers.cs
  src/Whim/Window/WindowManager.cs
  src/Whim/Workspace/IWorkspace.cs
  src/Whim/Workspace/Workspace.cs
Labels: bug, core

#828 Focus adjacent monitors with only minimized windows
  src/Whim.Tests/Butler/ButlerEventHandlersTests.cs
  src/Whim.Tests/Commands/CoreCommandsTests.cs
  src/Whim.Tests/Monitor/MonitorManagerTests.cs
  src/Whim/Butler/ButlerEventHandlers.cs
  src/Whim/Butler/IButler.cs
  src/Whim/Commands/CoreCommands.cs
  src/Whim/Monitor/IInternalMonitorManager.cs
  src/Whim/Monitor/MonitorManager.cs
  src/Whim/Window/WindowManager.cs
Labels: bug, core

#832 Fix docs commit linting
  .github/workflows/docs_commit.yml
  docs/docs/customize/logging.md
Labels: engineering

#831 Some docs suggestions
  docs/docs/contribute/docs.md
  docs/docs/customize/commands.md
  docs/docs/customize/filtering.md
  docs/docs/customize/keybinds.md
  docs/docs/customize/routing.md
  docs/docs/customize/scripting.md
  docs/docs/customize/snippets.md
  docs/docs/customize/styling.md
  docs/docs/getting-started/inspiration.md
Labels: documentation

#837 Fix bar alignment
  src/Whim.Bar/BarWindow.xaml
Labels: bug, bar

#836 Prefer using internal state when updating the focused monitor
  src/Whim.CommandPalette.Tests/CommandPaletteCommandsTests.cs
  src/Whim.CommandPalette/CommandPaletteCommands.cs
  src/Whim.Tests/Monitor/MonitorManagerTests.cs
  src/Whim/Monitor/MonitorManager.cs
Labels: bug, core

#838 Always perform a layout, even if the layout hasn't changed
  src/Whim/Workspace/Workspace.cs
Labels: bug, core
