Repository dalyIsaac/Whim, pull requests merged in 2024-07, with the labels that each got.

#935 Add window garbage collection back in
  src/Whim.TestUtils/StoreCustomization.cs
  src/Whim.Tests/Store/WorkspaceSector/WorkspaceSectorTests.cs
  src/Whim/Store/RootSector/MutableRootSector.cs
  src/Whim/Store/RootSector/RootSector.cs
  src/Whim/Store/Store.cs
  src/Whim/Store/WorkspaceSector/WorkspaceSector.cs
Labels: bug, core

#940 Bump Windows App SDK and CsWin32
  Directory.Packages.props
Labels: core, dependencies

#945 Reduce calls to the main thread
  src/Whim.Tests/Store/Root/MutableSectorTests.cs
  src/Whim.Tests/Store/Root/StoreTests.cs
  src/Whim.Tests/Store/WindowSector/Transforms/WindowMovedTransformTests.cs
  src/Whim/Store/RootSector/MutableRootSector.cs
  src/Whim/Store/SectorBase.cs
  src/Whim/Store/Store.cs
Labels: bug, core

#947 Reduce logging noise
  src/Whim/Store/MonitorSector/MonitorEventListener.cs
  src/Whim/Store/MonitorSector/MonitorSector.cs
  src/Whim/Store/RootSector/MutableRootSector.cs
  src/Whim/Store/Store.cs
  src/Whim/Store/WindowSector/Transforms/WindowAddedTransform.cs
  src/Whim/Store/WindowSector/WindowEventListener.cs
  src/Whim/Store/WindowSector/WindowSector.cs
  src/Whim/Store/WorkspaceSector/Transforms/InitializeWorkspacesTransform.cs
  src/Whim/Store/WorkspaceSector/WorkspaceSector.cs
  src/Whim/Utils/WhimException.cs
Labels: bug, core

#949 Optimize event dispatching
  src/Whim/Store/RootSector/MutableRootSector.cs
  src/Whim/Store/Store.cs
Labels: bug, core

#948 Add support for composite and negated komorebi rules
  app_rules/generate_app_rules.py
Labels: enhancement, auto app rules

#950 Automated app-rules upgrades
  src/Whim/Filter/DefaultFilteredWindowsKomorebi.g.cs
Labels: auto app rules

#951 Update komorebi application rules license
  THIRD-PARTY-NOTICES.TXT
  app_rules/generate_app_rules.py
Labels: auto app rules, engineering

#952 Automated app-rules upgrades
  src/Whim/Filter/DefaultFilteredWindowsKomorebi.g.cs
Labels: auto app rules

#954 ActivateAdjacent now skips all active workspaces
  src/Whim.Tests/Store/MapSector/MapPickersTests.cs
  src/Whim/Store/MapSector/MapPickers.cs
Labels: bug, core

#957 Fix Firefox handling with custom window event logic
  docs/docs/getting-started/troubleshooting.md
  docs/docs/plugins/focus-indicator.md
  docs/docs/toc.yml
  src/Whim.Tests/Store/WindowSector/Processors/FirefoxWindowProcessorTests.cs
  src/Whim.Tests/Store/WindowSector/Processors/WindowProcessorManagerTests.cs
  src/Whim.Tests/Store/WindowSector/Transforms/WindowMovedTransformTests.cs
  src/Whim.Tests/Store/WindowSector/WindowEventListenerTests.cs
  src/Whim/Filter/DefaultFilteredWindows.cs
  src/Whim/Native/HWND.cs
  src/Whim/Store/Transform.cs
  src/Whim/Store/WindowSector/IWindowSector.cs
  src/Whim/Store/WindowSector/Processors/FirefoxWindowProcessor.cs
  src/Whim/Store/WindowSector/Processors/IWindowProcessor.cs
  src/Whim/Store/WindowSector/Processors/WindowProcessorManager.cs
  src/Whim/Store/WindowSector/Processors/WindowProcessorResult.cs
  src/Whim/Store/WindowSector/Transforms/WindowMovedTransform.cs
  src/Whim/Store/WindowSector/Transforms/WindowRemovedTransform.cs
  src/Whim/Store/WindowSector/WindowEventListener.cs
  src/Whim/Store/WindowSector/WindowSector.cs
  src/Whim/Window/IWindowManager.cs
  src/Whim/Window/WindowManager.cs
Labels: enhancement, core

#956 Automated app-rules upgrades
  src/Whim/Filter/DefaultFilteredWindowsKomorebi.g.cs
Labels: auto app rules

#958 Don't apply custom Firefox processing on startup
  src/Whim.Tests/Store/MapSector/Transforms/InitializeWorkspacesTransformTests.cs
  src/Whim.Tests/Store/WindowSector/Processors/FirefoxWindowProcessorTests.cs
  src/Whim.Tests/Store/WindowSector/WindowPickersTests.cs
  src/Whim/Store/WindowSector/IWindowSector.cs
  src/Whim/Store/WindowSector/Processors/FirefoxWindowProcessor.cs
  src/Whim/Store/WindowSector/WindowPickers.cs
  src/Whim/Store/WindowSector/WindowSector.cs
  src/Whim/Store/WorkspaceSector/Transforms/InitializeWorkspacesTransform.cs
Labels: bug, core
